### ISSUE TITLE
"Batching" all changes into one event

### ISSUE THREAD

**Issue by zachahn** [filewatcher/filewatcher#114]
Hello!

Would you be interested in a patch that adds something like a `batch` option? I'd like to be notified of every change, but it'd be helpful for my use case if I saw all the changes at once.

I'm imagining updating the `trigger_changes` method to do something like this:

```ruby
if @batch
  on_update.call(@changes)
else
  changes = @every ? @changes : @changes.first(1)
  changes.each do |filename, event|
    on_update.call(filename, event)
  end
end
```

I'm not sure if `@batch` or if `@every` should take priority. I can't think of what behavior should be if both options are enabled.

Thank you!

**Comment by AlexWayfer** [comment]
Hello!

It's a nice idea! I had something like this in my minds, but without implementation.

You got the main dilemma: `every` vs. `batch`.

And there are issues with Ruby DSL and CLI.

I personally think that we should move to simplicity, and if we replace `every` in Ruby DSL with `batch`…

Oh, I remember my thoughts: we can pass into block (Ruby DSL) all changes as a Hash and that's all.

So, if we have enabled `every` CLI option — we'll make an action for every change (from block argument, like `Hash#each`). If not — only for the first.

Because, honestly, I can't imagine how to process `batch` option for CLI.

So, we can have a single argument for Ruby DSL — `changes` (Hash), without `batch` or `every` options (if you want to implement any of this — it's not too hard, just use `each` or `break`). And leave `every` option for CLI, implementing there `each` or `break` (depending on `true` or `false` value).

By the way, I have plans to take CLI out into plugin. But if you want — you can implement described behavior, or just let me know and I can try to do this. Before CLI as plugin.

**Comment by zachahn** [comment]
I pushed up PR #115, let me know what you think and if I misunderstood you! I think I did it a little different from what you said, but I think it should do what you want.

One note, I didn't look into the broken "pause" tests yet. I'm happy to look into it, if you have any ideas why they're broken, please let me know :)

And please feel free to edit the PR! I believe you should be able to change it.

**Comment by AlexWayfer** [comment]
Resolved in the mentioned PR. Thank you again.
