### ISSUE TITLE
Question regarding API

### ISSUE THREAD

**Issue by devpixde** [filewatcher/filewatcher#202]
I tried to follow the API examples.

In my case  "changes" is always just a string (it's the absolute path to the file) not an Object.

So all examples throw errors like this:  undefined method `each' for "/opt/project/watchthis/test.text"

I am on Ruby 2.7 on MacOS but Ruby is Running in a Docker Container.

What am I doing wrong? Am I missing something?

Regards

**Comment by blunt-c** [comment]
I had the same problem today. I think it's because you have installed the latest release version of the gem v1.1.1. - this is actually quite old. The latest beta version is 2.0.0beta5.

If you run ```gem install filewatcher --pre``` then the latest beta will be installed. I found examples work perfectly then.

**Comment by AlexWayfer** [comment]
Yep, that's correct, thank you @blunt-c 

You can see the actual version here:

![image](https://user-images.githubusercontent.com/6510020/147853711-72d3db8b-bf98-4720-9a4a-ca004ba106d2.png)

And the README in the `main` branch (on the default repo page) is always the most fresh and not always actual.

By the way, you can see the README for your version by selecting tag above the file list, like this: https://github.com/filewatcher/filewatcher/tree/v1.1.1

Version 2 (major update) has significant changes (that's why its' major update), like splitting the single gem into multiple ones (take out CLI, for example). And there are already few betas, as you can see.

I hope, we'll release a stable version soon.

**Comment by AlexWayfer** [comment]
The whole ecosystem has been released. :tada:
